blank_issues_enabled: false
contact_links:
  - name: Guía para creación de issues
    url: https://play.typeracer.com?universe=lang_es&rt=2f9o34mwgg
    about: Breve manual de ciclo de vida de un issue
