blank_issues_enabled: false
contact_links:
  - name: Aca se reportan los issues los de testing
    url: https://play.typeracer.com?universe=lang_es&rt=26kjnerv24
    about: Es de carrera esta página.
