name: Feature Request
description: Request a new feature
title: "[Feature Request]: "
labels: ["new feature"]
assignees:
  - 
body:
  - type: input
    id: contact2
    attributes:
      label: ¿Qué cliente lo solicita?
      placeholder: Lo solicita el cliente...
  - type: textarea
    id: contact
    attributes:
      label: Descripción 💬
      description: Describir la implementación a proponer
      placeholder: Se propone...
    validations:
      required: true
  - type: checkboxes
    id: terms1
    attributes:
      label: ¿Requiere cotización? 💲
      description: En caso positivo, agregar también el label correspondiente 🏷
      options:
        - label: Sí
  - type: input
    id: contact1
    attributes:
      label: Plazos solicitados por el cliente
      description: Mencionar plazos o fechas para estimar y priorizar
      placeholder: El cliente pide que se pase un estimativo antes de...
  - type: markdown
    attributes:
      value: |
        ##
        ### Recordar:
        #### - Agregar los labels involucrados en la propuesta 🏷
        #### - Seleccionar Projects-> To do 👉
        #### - Añadir capturas, imagenes y/o videos que ayuden al proceso de validación y desarrollo 📷📹🎞
        ##
      
