name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - Alejox7
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Instancia
      description: En que instancia ocurrio el problema?
      placeholder: INSTANCIA.ucontactcloud.com
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: Cual fue el problema?
      description: Contame los detalles
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: Cual es la version de uContact en la que ocurre el problema?
      placeholder: 4.6xx
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Copie y pegue el log. Este se formateara automaticamente como codigo.
      render: shell
  - type: textarea
    id: pasos
    attributes:
      label: Pasos para reproducir el incidente
      description:  Pasos para reproducir el incidente
      placeholder: 1- Primero se entra como supervisor a ...
  - type: checkboxes
    id: terms
    attributes:
      label: Fue reproducido en otras instancias?
      description: En caso de no ser reproducido agregar el label Triage
      options:
        - label: Si
