name: Feature Request
description: Request a new feature
title: "[Improvement]: "
labels: ["improvement"]
assignees:
  - 
body:
  - type: markdown
    attributes:
      value: |
        ### Recordar:
        #### - Agregar los labels involucrados en la propuesta
        #### - Seleccionar Projects-> To do
        #### - Añadir capturas, imagenes y/o videos que ayuden al proceso de desarrollo.
        ##
  - type: input
    id: contact
    attributes:
      label: Instancia
      description: Describir la mejora a proponer
      placeholder: Quiero mas bananas porque...
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Versión
      description: 
      placeholder: 6.4xx
    validations:
      required: true
  - type: dropdown
    id: channel
    attributes:
      label: ¿En qué canales ocurre este problema?
      multiple: true
      description: Agregar los labels correspondientes a los canales
      options:
        - Telefonía
        - Webchat
        - SMS/Whatsapp
        - Email
        - Facebook/Messenger
